# File containing all the Extended Kalamn Filter constants.
# This is going to be used during system initialization as well as update.
# The values of the constants have been tuned very precisly, please be carefull
# changing the constants.

# ********* Timings and Rates ***********

# The time of the initialisation step
/proc_navigation/ekf/t_init : 0.5
# Flag that states if we should estimate the gravity with inertial measures or
# manually
/proc_navigation/ekf/manual_gravity : true
# Value of the gravity if set manually
/proc_navigation/ekf/gravity : 9.8
# The angle between the heading of the AUV and the DVL in deg
/proc_navigation/ekf/heading_shift_dvl : -45
# The temperature of the atmostphere in K
/proc_navigation/ekf/air_temperature : 298.15 # [K] (25 degrees Celcius)
# The pressure at the surface of the water in [PA]
/proc_navigation/ekf/surface_pressure : 101325

# ********* Control and Tuning ***********

# Is the measure of gravity activated
/proc_navigation/ekf/active_gravity : true
# Is the measure of magnetometer activated
/proc_navigation/ekf/active_mag : true
# Is the measure of DVL activated
/proc_navigation/ekf/active_dvl : true
# Is the measure of barometer activated
/proc_navigation/ekf/active_baro : true

# ********* Measure variances ***********

# Gravity measurements variances
/proc_navigation/ekf/sigma_meas_gravity : 0.010
# Magneto measurements variances
/proc_navigation/ekf/sigma_meas_mag : 0.010
# DVL measurements variances
/proc_navigation/ekf/sigma_meas_dvl_x : 0.10
/proc_navigation/ekf/sigma_meas_dvl_y : 0.10
/proc_navigation/ekf/sigma_meas_dvl_z : 0.10
# Baro measurements variances
/proc_navigation/ekf/sigma_meas_baro : 0.010

# Kalman initialization states uncertainty
/proc_navigation/ekf/sigma0_pos_x : 0.01
/proc_navigation/ekf/sigma0_pos_y : 0.01
/proc_navigation/ekf/sigma0_pos_z : 0.01
/proc_navigation/ekf/sigma0_vel_x : 0.01
/proc_navigation/ekf/sigma0_vel_y : 0.01
/proc_navigation/ekf/sigma0_vel_z : 0.01
/proc_navigation/ekf/sigma0_rho_x : 0.01
/proc_navigation/ekf/sigma0_rho_y : 0.01
/proc_navigation/ekf/sigma0_rho_z : 0.01
/proc_navigation/ekf/sigma0_bias_acc : 0.1
/proc_navigation/ekf/sigma0_bias_gyr : 0.001
/proc_navigation/ekf/sigma0_bias_baro : 0.001

# Propagation uncertainty
/proc_navigation/ekf/sigma_meas_acc : 15.0
/proc_navigation/ekf/sigma_meas_gyr : 0.01
/proc_navigation/ekf/sigma_walk_bias_acc : 0.001
/proc_navigation/ekf/sigma_walk_bias_gyr : 0.001
/proc_navigation/ekf/sigma_walk_bias_baro : 0.001

# ********* AUV Physics ***********

# Distance frmo IMU to devices in body frame (NED)
/proc_navigation/ekf/l_pd: [0.0, 0.0, 0.15] # IMU - DVL
/proc_navigation/ekf/l_pp: [0.0, -0.10, -0.5] # IMU - DVL

# ********* Stationnary State Detection ***********

/proc_navigation/ekf/crit_station_acc: 1.0
/proc_navigation/ekf/crit_station_norm: 1.0

# ********* Signs of devices measures ***********
# According to the device orientation, the sign can change, set the values here
/proc_navigation/device_sign/imu/x: 1
/proc_navigation/device_sign/imu/y: -1
/proc_navigation/device_sign/imu/z: -1
/proc_navigation/device_sign/mag/x: 1
/proc_navigation/device_sign/mag/y: -1
/proc_navigation/device_sign/mag/z: -1
