# File contains the configuration for the proc_navigation node.
# For instance, it sets the name of the subscribed topic and other useful conf.

# ********* Topic Names ***********

/proc_navigation/topics/baro: "/provider_can/barometer_fluidpress_msgs"
/proc_navigation/topics/dvl: "/provider_dvl/twist"
/proc_navigation/topics/imu: "/provider_imu/imu"
/proc_navigation/topics/mag: "/provider_imu/magnetic_field"

/proc_navigation/simulation/active: true
/proc_navigation/simulation/dt_imu: 0.01 # 100 Hz
/proc_navigation/simulation/dt_mag: 0.01 # 100 Hz
/proc_navigation/simulation/dt_dvl: 0.2857142857142857 # 3.5Hz
/proc_navigation/simulation/dt_baro: 0.072 # 13.8Hz
